DATA_SPACE:
    MODULE: physion.data_space
    SEEDS: (0,1,2,3)
    KWARGS: 
        pretraining:
            scenarios: ['support_interesting']
            train:
                dir: 'curiophysion_train_data'
            test:
                dir: 'curiophysion_test_data'
        readout:
            scenarios: ['Support_split']
            train:
                dir: 'physion_train_data/readout_training'
            test:
                dir: 'physion_test_data/model_testing'
        pretraining_protocols: ['only']
        readout_protocol: 'full'

PRETRAINING:
    OBJECTIVE_MODULE: physion.objective.CSWM
    MODEL_NAME: 'CSWM'
    TRAIN_STEPS: 100
    BATCH_SIZE: 32
    TRAIN:
        LR: 5.e-4
    MODEL: 
        ENCODER: 'medium'
        SIGMA: 0.5
        HINGE: 1. 
        HIDDEN_DIM: 512
        EMBEDDING_DIM: 128
        NUM_OBJECTS: 10
        ACTION_DIM: 0 
        IGNORE_ACTION: True
    DATA:
        STATE_LEN: 7
        SEQ_LEN: 25
        IMSIZE: 224
        SUBSAMPLE_FACTOR: 6

EXTRACTION:
    OBJECTIVE_MODULE: physion.objective.CSWM

CONFIG:
    EXPERIMENT_NAME: 'curiophysion-v3'
