OUTPUT_DIR: '/data1/eliwang/curiophysopt'

DATA_SPACE:
    MODULE: physion.data.data_space
    KWARGS: 
        cfg_file: 'curiophysion.yaml'

OBJECTIVE:
    MODULE: physion.FROZEN
    NAME: 'pVGG_LSTMObjective'

CONFIG:
    TRAIN_STEPS: 100
    BATCH_SIZE: 32
    TRAIN:
        LR: 1.e-2
    DATA: 
        STATE_LEN: 7
        SEQ_LEN: 25
        IMSIZE: 224
        SUBSAMPLE_FACTOR: 6
