DATA_SPACE:
    MODULE: physion.data_space
    SEEDS: (0,)
    KWARGS:
        # scenarios: ['Collide', 'Contain', 'Dominoes', 'Drape', 'Drop', 'Link', 'Roll', 'Support']
        scenarios: ['Collide']
        pretraining:
            train:
                dir: 'testdata'
            test:
                dir: 'testdata'
        readout:
            train:
                dir: 'testdata'
            test:
                dir: 'testdata'
        pretraining_protocols: ['only']
        # pretraining_protocols: ['all']
        readout_protocol: 'minimal'

SKIP_PRETRAINING: True
PRETRAINING:
    VAL_FREQ: 5000
    CKPT_FREQ: 5000
    OBJECTIVE_MODULE: physion.objective.FitVidExt
    MODEL_NAME: 'FitVid'
    TRAIN_STEPS: 1000000
    BATCH_SIZE: 2
    TRAIN:
        LR: 1.e-3
        ACCUMULATION_BATCH_SIZE: 128
    MODEL:
        CUSTOM_CONFIG: '/mnt/fs3/rmvenkat/code/physion/configs/FitVid/fitvid.yaml'
    DATA:
        IMSIZE: 64
#        STATE_LEN: 7
#        SEQ_LEN: 25
        STATE_LEN: 5
        SEQ_LEN: 16
        SUBSAMPLE_FACTOR: 9

EXTRACTION:
    OBJECTIVE_MODULE: physion.objective.FitVidExt

READOUT:
    # PROTOCOLS: ['simulated']
    PROTOCOLS: ['simulated', 'observed']

CONFIG:
    EXPERIMENT_NAME: 'physion-fitvid-1'