DATA_SPACE:
    MODULE: physion.data_space
    SEEDS: (0,)
    KWARGS:
        # scenarios: ['Collide', 'Contain', 'Dominoes', 'Drape', 'Drop', 'Link', 'Roll', 'Support']
        scenarios: ['Collide'] 
        pretraining:
            train:
                dir: 'physion_data/pretraining_train'
            test:
                dir: 'physion_data/pretraining_val'
        readout:
            train:
                dir: 'physion_data/readout_train_redyellow'
            test:
                dir: 'physion_data/readout_test_redyellow'
        pretraining_protocols: ['only']
        readout_protocol: 'minimal'

PRETRAINING:
    OBJECTIVE_MODULE: physion.objective.FitVid
    MODEL_NAME: 'FitVid'
    TRAIN_STEPS: 1000
    BATCH_SIZE: 8
    TRAIN:
        LR: 1.e-2
    DATA:
        STATE_LEN: 7
        SEQ_LEN: 25
        IMSIZE: 64
        SUBSAMPLE_FACTOR: 6

EXTRACTION:
    OBJECTIVE_MODULE: physion.objective.FitVid

READOUT:
    PROTOCOLS: ['simulated']

CONFIG:
    EXPERIMENT_NAME: 'physion-fitvid'
    POSTGRES:
        DBNAME: 'physion-physopt'
