DATA_SPACE:
    MODULE: physion.data_space
    SEEDS: [0]
    KWARGS:
        scenarios: ['Collide']
        file_pattern: '*.hdf5'
        pretraining:
            train:
                dir: '/mnt/fs3/rmvenkat/data/physion_example_data/pretraining_train'
            test:
                dir: '/mnt/fs3/rmvenkat/data/physion_example_data/pretraining_val'
        readout:
            train:
                dir: '/mnt/fs3/rmvenkat/data/physion_example_data/readout_train'
            test:
                dir: '/mnt/fs3/rmvenkat/data/physion_example_data/readout_test'
        pretraining_protocols: ['only']
        readout_protocol: 'full'

PRETRAINING:
    OBJECTIVE_MODULE: physion.objective.FROZEN
    MODEL_NAME: 'pVGG_MLP'
    TRAIN_STEPS: 2
    BATCH_SIZE: 32
    TRAIN:
        LR: 1.e-2
    DATA: 
        STATE_LEN: 7
        SEQ_LEN: 25
        IMSIZE: 224
        SUBSAMPLE_FACTOR: 6

EXTRACTION:
    OBJECTIVE_MODULE: physion.objective.FROZEN

READOUT:
    OBJECTIVE_MODULE: physion.objective.objective

CONFIG:
    DBNAME: 'physopt-example'
