DATA_SPACE:
    MODULE: physion.data_space
    SEEDS: (0,)
    KWARGS: 
        pretraining_train_dir: 'curiophysion_train_data'
        pretraining_test_dir: 'curiophysion_test_data'
        pretraining_scenarios: ('support_interesting',)
        pretraining_protocols: ('only',) 
        readout_train_dir: 'physion_train_data/readout_training'
        readout_test_dir: 'physion_test_data/model_testing'
        readout_scenarios: ('Support_split',)
        readout_protocol: 'full'

PRETRAINING:
    OBJECTIVE_MODULE: physion.objective.FROZEN
    MODEL_NAME: 'pVGG_MLP'
    TRAIN_STEPS: 100
    BATCH_SIZE: 32
    TRAIN:
        LR: 1.e-2
    DATA: 
        STATE_LEN: 7
        SEQ_LEN: 25
        IMSIZE: 224
        SUBSAMPLE_FACTOR: 6

EXTRACTION:
    OBJECTIVE_MODULE: physion.objective.FROZEN

CONFIG:
    EXPERIMENT_NAME: 'curiophysion-v3'
